Repository firedrakeproject/gusto_case_studies, pull requests merged in 2024-09, with the labels that each got.

#24 Pick up move to Omega in gusto main
  compressible_euler/dry_baroclinic_sphere.py
  compressible_euler/moist_baroclinic_channel.py
Labels: bug, external issue, case study

#26 Terminator plots
  transport/figures/terminator_toy.png
  transport/plotting/plot_terminator_toy.py
  transport/terminator_toy.py
Labels: bug, plotting script, figure, case study

#28 Fix boolean argument in Nair Lauritzen divergent
  case_studies/transport/nair_lauritzen_divergent.py
  case_studies/transport/test_transport.py
Labels: bug, tidying
